# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui\main.ui'
#
# Created: Mon Mar 23 22:58:31 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1070, 683)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/assets/icons/Gw2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.central_widget = QtGui.QWidget(MainWindow)
        self.central_widget.setStyleSheet("")
        self.central_widget.setObjectName("central_widget")
        self.central_layout = QtGui.QVBoxLayout(self.central_widget)
        self.central_layout.setSpacing(0)
        self.central_layout.setContentsMargins(0, 0, 0, 0)
        self.central_layout.setObjectName("central_layout")
        self.mainCanvasContainer_widget = QtGui.QWidget(self.central_widget)
        self.mainCanvasContainer_widget.setObjectName("mainCanvasContainer_widget")
        self.mainCanvasContainer_layout = QtGui.QGridLayout(self.mainCanvasContainer_widget)
        self.mainCanvasContainer_layout.setContentsMargins(0, 0, 0, 0)
        self.mainCanvasContainer_layout.setSpacing(0)
        self.mainCanvasContainer_layout.setContentsMargins(0, 0, 0, 0)
        self.mainCanvasContainer_layout.setObjectName("mainCanvasContainer_layout")
        self.mainCanvas_scrollArea = QtGui.QScrollArea(self.mainCanvasContainer_widget)
        self.mainCanvas_scrollArea.setFrameShape(QtGui.QFrame.Box)
        self.mainCanvas_scrollArea.setFrameShadow(QtGui.QFrame.Sunken)
        self.mainCanvas_scrollArea.setLineWidth(1)
        self.mainCanvas_scrollArea.setWidgetResizable(True)
        self.mainCanvas_scrollArea.setObjectName("mainCanvas_scrollArea")
        self.mainCanvas_widget = QtGui.QWidget()
        self.mainCanvas_widget.setGeometry(QtCore.QRect(0, 0, 1068, 640))
        self.mainCanvas_widget.setObjectName("mainCanvas_widget")
        self.mainCanvas_scrollArea.setWidget(self.mainCanvas_widget)
        self.mainCanvasContainer_layout.addWidget(self.mainCanvas_scrollArea, 0, 0, 1, 1)
        self.central_layout.addWidget(self.mainCanvasContainer_widget)
        self.serverAddress_widget = QtGui.QWidget(self.central_widget)
        self.serverAddress_widget.setMaximumSize(QtCore.QSize(16777215, 20))
        self.serverAddress_widget.setObjectName("serverAddress_widget")
        self.serverAddress_layout = QtGui.QHBoxLayout(self.serverAddress_widget)
        self.serverAddress_layout.setSpacing(0)
        self.serverAddress_layout.setContentsMargins(0, 0, 0, 0)
        self.serverAddress_layout.setContentsMargins(0, 0, 0, 0)
        self.serverAddress_layout.setObjectName("serverAddress_layout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.serverAddress_layout.addItem(spacerItem)
        self.serverAddress = QtGui.QLabel(self.serverAddress_widget)
        self.serverAddress.setText("")
        self.serverAddress.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.serverAddress.setObjectName("serverAddress")
        self.serverAddress_layout.addWidget(self.serverAddress)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.serverAddress_layout.addItem(spacerItem1)
        self.central_layout.addWidget(self.serverAddress_widget)
        MainWindow.setCentralWidget(self.central_widget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1070, 21))
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.actionSettings = QtGui.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionCompact = QtGui.QAction(MainWindow)
        self.actionCompact.setObjectName("actionCompact")
        self.actionAlway_On_Top = QtGui.QAction(MainWindow)
        self.actionAlway_On_Top.setObjectName("actionAlway_On_Top")
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "GW2 Events", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings.setText(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCompact.setText(QtGui.QApplication.translate("MainWindow", "Compact Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAlway_On_Top.setText(QtGui.QApplication.translate("MainWindow", "Alway On Top", None, QtGui.QApplication.UnicodeUTF8))

import assets_rc
